### ISSUE TITLE
allow escope options to be passed through

### ISSUE THREAD

**Issue by welelay** [mazurov/eslevels#6]
I've moved some of my files to ES6, with "import" statements.
This is accepted by escope only with the options `{ ecmaVersion: 6, sourceType: 'module' }` (see [this comment](https://github.com/estools/escope/issues/106#issuecomment-222329430)).
Now eslevels doesn't pass options to escope [line 314](https://github.com/mazurov/eslevels/blob/master/eslevels.js#L314).
Adding the option solved my issue (confirmed by patching in eslevels.js in `/usr/lib/node_modules`)

Would you consider adding  the option? Maybe an `escope` field in the eslevels options...
Thanks,
Eric

**Comment by elelay** [comment]
See fix in #7

**Comment by mazurov** [comment]
Fixed in v0.4.0. Thanks, @elelay

**Comment by elelay** [comment]
cool!
Thanks for the quick release :-)
